### ISSUE TITLE
Hosting copyrighted code.

### ISSUE THREAD

**Issue by chisely** [alejandromarcu/DominoTrack#2]
Hello Alejandro

I am the author of CurvedUI Unity asset (https://assetstore.unity3d.com/en/#!/content/53258) that you have made public on your repository at https://github.com/alejandromarcu/DominoTrack/tree/master/DominoTrack/Assets/CurvedUI

Unity AssetStore EULA does not allow end-users to make the code publicly available.  See relevant section 2.2.1 of AssetStore EULA here: https://unity3d.com/legal/as_terms

Please remove the copyrighted code from your public repository as soon as possible.  If this won't happen within 48hrs, I will send a DMCA Takedown Notice to Github, as you're violating their Terms of Service by making copyrighted code public.

Thank you.
Daniel Karcher

**Comment by alejandromarcu** [comment]
I just removed it

**Comment by chisely** [comment]
Thank you!
